etcd_endpoint_ips: |-
  {% for item in groups['etcd'] -%}
    {{ hostvars[item]['access_ip'] | default(hostvars[item]['ip'] | default(hostvars[item]['ansible_default_ipv4']['address'])) }}{% if not loop.last %},{% endif %}
  {%- endfor %}