---

- hosts: k8s-cluster
  tasks:
    - name: modify resolv.conf
      command: 'sed -i /^[^#]*search*/s/^/\#/g /etc/resolv.conf'

- hosts: kube-master[0]
  tasks:
    - name: fetch config
      fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "./config"
        flat: yes

- hosts: k8s-cluster
  roles:
    - kubesphere-defaults
    - prepare/nodes
    - download

- hosts: kube-master[0]
  roles:
    - kubesphere-defaults
#    - { role: storages/QingCloud-CSI, when: "qingcloud_csi_enabled == true" }
#    - { role: storages/NeonSAN-CSI, when: "neonsan_csi_enabled == true" }
#    - { role: storages/LocalVolume, when: "local_volume_provisioner_enabled == true" }
    - { role: storages/GlusterFS, when: "glusterfs_provisioner_enabled == true" }
    - { role: storages/CephRBD, when: "ceph_rbd_enabled == true" }
    - { role: storages/NFS-Client, when: "nfs_client_enable == true" }
#    - { role: VPA, when: "vertical_pod_autoscaler_enable == true" }

- hosts: etcd[0]
  roles:
    - etcd_backup

- hosts: kube-master[0]
  roles:
    - kubesphere-defaults
    - { role: qingcloud_controller_manager, when: "qingcloud_lb_enable == true" }
    - ks-installer